export default {
    // Common
    common: {
      app_name: 'نظام HCP للإدارة',
      loading: 'جارِ التحميل...',
      save: 'حفظ',
      cancel: 'إلغاء',
      delete: 'حذف',
      edit: 'تعديل',
      view: 'عرض',
      add: 'إضافة',
      search: 'بحث',
      filter: 'تصفية',
      reset: 'إعادة ضبط',
      export: 'تصدير',
      actions: 'إجراءات',
      confirm: 'تأكيد',
      back: 'رجوع',
      next: 'التالي',
      yes: 'نعم',
      no: 'لا',
      close: 'إغلاق',
      logout: 'تسجيل الخروج',
      all: 'الكل',
      welcome: 'مرحباً',
      settings: 'الإعدادات',
      profile: 'الملف الشخصي',
      dark_mode: 'الوضع الداكن',
      light_mode: 'الوضع الفاتح',
      required: 'مطلوب',
      optional: 'اختياري',
      status: 'الحالة',
      date: 'التاريخ',
      amount: 'المبلغ',
      price: 'السعر',
      total: 'المجموع',
      name: 'الاسم',
      email: 'البريد الإلكتروني',
      phone: 'الهاتف',
      address: 'العنوان',
      notes: 'ملاحظات',
      description: 'الوصف',
      category: 'الفئة',
      id: 'المعرف'
    },
    
    // Auth
    auth: {
      login: 'تسجيل الدخول',
      login_to_account: 'تسجيل الدخول إلى حسابك',
      forgot_password: 'نسيت كلمة المرور؟',
      reset_password: 'إعادة تعيين كلمة المرور',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      confirm_password: 'تأكيد كلمة المرور',
      login_error: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
      logout_success: 'تم تسجيل الخروج بنجاح',
      session_expired: 'انتهت جلستك بسبب عدم النشاط',
      reset_password_instructions: 'أدخل عنوان بريدك الإلكتروني وسنرسل لك رابطًا لإعادة تعيين كلمة المرور',
      reset_password_success: 'تم إرسال بريد إلكتروني لإعادة تعيين كلمة المرور. تحقق من صندوق الوارد الخاص بك.'
    },
    
    // Navigation
    nav: {
      dashboard: 'لوحة التحكم',
      customers: 'العملاء',
      suppliers: 'الموردين',
      sales: 'المبيعات',
      products: 'المنتجات',
      accounting: 'الحسابات',
      reports: 'التقارير',
      users: 'المستخدمين',
      settings: 'الإعدادات'
    },
    
    // Dashboard
    dashboard: {
      title: 'لوحة التحكم',
      total_sales: 'إجمالي المبيعات',
      total_customers: 'إجمالي العملاء',
      total_products: 'المنتجات',
      pending_orders: 'الطلبات المعلقة',
      recent_orders: 'الطلبات الأخيرة',
      sales_overview: 'نظرة عامة على المبيعات',
      top_products: 'أفضل المنتجات',
      view_all: 'عرض الكل',
      from_last_month: 'من الشهر الماضي',
      from_last_week: 'من الأسبوع الماضي'
    },
    
    // Products
    products: {
      title: 'إدارة المنتجات',
      add_product: 'إضافة منتج',
      edit_product: 'تعديل المنتج',
      delete_product: 'حذف المنتج',
      product_name: 'اسم المنتج',
      product_category: 'الفئة',
      product_price: 'السعر',
      batch_codes: 'الباتش/الكود',
      add_batch_code: 'إضافة باتش/كود',
      filter_products: 'تصفية المنتجات',
      category_all: 'كل الفئات',
      category_constructional: 'إنشائية',
      category_external: 'خارجية',
      category_decorative: 'ديكورية',
      price_range: 'نطاق السعر',
      price_min: 'الحد الأدنى',
      price_max: 'الحد الأقصى',
      no_products_found: 'لم يتم العثور على منتجات',
      get_started_add_product: 'ابدأ بإضافة منتج جديد',
      product_added_success: 'تمت إضافة المنتج بنجاح',
      product_updated_success: 'تم تحديث المنتج بنجاح',
      product_deleted_success: 'تم حذف المنتج بنجاح',
      confirm_delete_product: 'هل أنت متأكد من رغبتك في حذف هذا المنتج؟ لا يمكن التراجع عن هذا الإجراء.',
      enter_batch_code: 'أدخل الباتش/الكود',
      showing: 'عرض',
      to: 'إلى',
      of: 'من',
      products: 'منتج',
      product_details: 'تفاصيل المنتج'
    },
    
    // Customers
    customers: {
      title: 'إدارة العملاء',
      add_customer: 'إضافة عميل',
      edit_customer: 'تعديل العميل',
      delete_customer: 'حذف العميل',
      customer_name: 'اسم العميل',
      customer_type: 'نوع العميل',
      phone_number: 'رقم الهاتف',
      address: 'العنوان',
      discount_rate: 'معدل الخصم',
      type_corporate: 'مؤسسات/مشاريع',
      type_retail: 'محلات تجارية',
      type_individual: 'أفراد',
      no_customers_found: 'لم يتم العثور على عملاء',
      get_started_add_customer: 'ابدأ بإضافة عميل جديد',
      customer_added_success: 'تمت إضافة العميل بنجاح',
      customer_updated_success: 'تم تحديث العميل بنجاح',
      customer_deleted_success: 'تم حذف العميل بنجاح',
      confirm_delete_customer: 'هل أنت متأكد من رغبتك في حذف هذا العميل؟ لا يمكن التراجع عن هذا الإجراء.',
      customer_details: 'تفاصيل العميل',
      total_orders: 'إجمالي الطلبات',
      total_spent: 'إجمالي المصروفات',
      last_order_date: 'تاريخ آخر طلب'
    },
    
    // Suppliers
    suppliers: {
      title: 'إدارة الموردين',
      add_supplier: 'إضافة مورد',
      edit_supplier: 'تعديل المورد',
      delete_supplier: 'حذف المورد',
      supplier_name: 'اسم المورد',
      phone_number: 'رقم الهاتف',
      address: 'العنوان',
      no_suppliers_found: 'لم يتم العثور على موردين',
      get_started_add_supplier: 'ابدأ بإضافة مورد جديد',
      supplier_added_success: 'تمت إضافة المورد بنجاح',
      supplier_updated_success: 'تم تحديث المورد بنجاح',
      supplier_deleted_success: 'تم حذف المورد بنجاح',
      confirm_delete_supplier: 'هل أنت متأكد من رغبتك في حذف هذا المورد؟ لا يمكن التراجع عن هذا الإجراء.',
      supplier_details: 'تفاصيل المورد'
    },
    
    // Sales
    sales: {
      title: 'إدارة المبيعات',
      invoices: 'الفواتير',
      create_invoice: 'إنشاء فاتورة',
      edit_invoice: 'تعديل الفاتورة',
      view_invoice: 'عرض الفاتورة',
      delete_invoice: 'حذف الفاتورة',
      invoice_number: 'رقم الفاتورة',
      order_number: 'رقم الطلب',
      invoice_date: 'تاريخ الفاتورة',
      due_date: 'تاريخ الاستحقاق',
      customer: 'العميل',
      select_customer: 'اختر العميل',
      products: 'المنتجات',
      add_product: 'إضافة منتج',
      select_product: 'اختر المنتج',
      quantity: 'الكمية',
      unit_price: 'سعر الوحدة',
      subtotal: 'المجموع الفرعي',
      discount: 'الخصم',
      tax: 'الضريبة',
      total: 'المجموع',
      payment_method: 'طريقة الدفع',
      payment_status: 'حالة الدفع',
      payment_notes: 'ملاحظات الدفع',
      payment_date: 'تاريخ الدفع',
      payment_amount: 'مبلغ الدفع',
      invoice_notes: 'ملاحظات الفاتورة',
      print_invoice: 'طباعة الفاتورة',
      download_invoice: 'تنزيل الفاتورة',
      send_invoice: 'إرسال الفاتورة',
      status_draft: 'مسودة',
      status_pending: 'معلق',
      status_processing: 'قيد المعالجة',
      status_delivered: 'تم التسليم',
      status_canceled: 'ملغي',
      status_returned: 'مرتجع',
      payment_status_paid: 'مدفوع',
      payment_status_partial: 'جزئي',
      payment_status_due: 'مستحق',
      payment_status_overdue: 'متأخر',
      payment_method_cash: 'نقدي',
      payment_method_bank_transfer: 'تحويل بنكي',
      payment_method_e_wallet: 'محفظة إلكترونية',
      payment_method_bank_check: 'شيك بنكي',
      deposit_amount: 'مبلغ العربون',
      deposit_method: 'طريقة دفع العربون',
      invoice_created_success: 'تم إنشاء الفاتورة بنجاح',
      invoice_updated_success: 'تم تحديث الفاتورة بنجاح',
      invoice_deleted_success: 'تم حذف الفاتورة بنجاح',
      confirm_delete_invoice: 'هل أنت متأكد من رغبتك في حذف هذه الفاتورة؟ لا يمكن التراجع عن هذا الإجراء.',
      return_invoice: 'فاتورة مرتجعات',
      create_return: 'إنشاء مرتجع',
      return_reason: 'سبب الإرجاع',
      return_date: 'تاريخ الإرجاع',
      return_products: 'المنتجات المرتجعة',
      return_amount: 'مبلغ الإرجاع',
      return_created_success: 'تم إنشاء المرتجع بنجاح'
    },
    
    // Accounting
    accounting: {
      title: 'الحسابات',
      customer_payments: 'مدفوعات العملاء',
      supplier_payments: 'مدفوعات الموردين',
      add_payment: 'إضافة دفعة',
      edit_payment: 'تعديل الدفعة',
      delete_payment: 'حذف الدفعة',
      payment_date: 'تاريخ الدفع',
      payment_amount: 'المبلغ',
      payment_method: 'طريقة الدفع',
      payment_reference: 'المرجع',
      payment_notes: 'ملاحظات',
      payment_type: 'النوع',
      payment_invoice: 'الفاتورة',
      payment_customer: 'العميل',
      payment_supplier: 'المورد',
      payment_added_success: 'تمت إضافة الدفعة بنجاح',
      payment_updated_success: 'تم تحديث الدفعة بنجاح',
      payment_deleted_success: 'تم حذف الدفعة بنجاح',
      confirm_delete_payment: 'هل أنت متأكد من رغبتك في حذف هذه الدفعة؟ لا يمكن التراجع عن هذا الإجراء.',
      customer_statement: 'كشف حساب العميل',
      supplier_statement: 'كشف حساب المورد',
      generate_statement: 'إنشاء كشف حساب',
      statement_period: 'فترة كشف الحساب',
      opening_balance: 'الرصيد الافتتاحي',
      closing_balance: 'الرصيد الختامي',
      transaction_date: 'التاريخ',
      transaction_type: 'النوع',
      transaction_reference: 'المرجع',
      transaction_description: 'الوصف',
      transaction_debit: 'مدين',
      transaction_credit: 'دائن',
      transaction_balance: 'الرصيد',
      print_statement: 'طباعة كشف الحساب',
      export_statement: 'تصدير كشف الحساب'
    },
    
    // Reports
    reports: {
      title: 'التقارير',
      sales_report: 'تقرير المبيعات',
      inventory_report: 'تقرير المخزون',
      financial_report: 'التقرير المالي',
      customer_report: 'تقرير العملاء',
      supplier_report: 'تقرير الموردين',
      date_range: 'النطاق الزمني',
      start_date: 'تاريخ البدء',
      end_date: 'تاريخ الانتهاء',
      generate_report: 'إنشاء التقرير',
      export_report: 'تصدير التقرير',
      print_report: 'طباعة التقرير',
      total_sales: 'إجمالي المبيعات',
      total_cost: 'إجمالي التكلفة',
      total_profit: 'إجمالي الربح',
      profit_margin: 'هامش الربح',
      top_selling_products: 'المنتجات الأكثر مبيعاً',
      top_customers: 'كبار العملاء',
      monthly_sales: 'المبيعات الشهرية',
      sales_by_category: 'المبيعات حسب الفئة',
      sales_by_payment_method: 'المبيعات حسب طريقة الدفع'
    },
    
    // Users
    users: {
      title: 'إدارة المستخدمين',
      add_user: 'إضافة مستخدم',
      edit_user: 'تعديل المستخدم',
      delete_user: 'حذف المستخدم',
      user_name: 'الاسم',
      user_email: 'البريد الإلكتروني',
      user_password: 'كلمة المرور',
      user_confirm_password: 'تأكيد كلمة المرور',
      user_role: 'الدور',
      user_status: 'الحالة',
      role_admin: 'مدير',
      role_supervisor: 'مشرف',
      role_user: 'مستخدم',
      status_active: 'نشط',
      status_inactive: 'غير نشط',
      last_login: 'آخر تسجيل دخول',
      created_date: 'تاريخ الإنشاء',
      no_users_found: 'لم يتم العثور على مستخدمين',
      user_added_success: 'تمت إضافة المستخدم بنجاح',
      user_updated_success: 'تم تحديث المستخدم بنجاح',
      user_deleted_success: 'تم حذف المستخدم بنجاح',
      confirm_delete_user: 'هل أنت متأكد من رغبتك في حذف هذا المستخدم؟ لا يمكن التراجع عن هذا الإجراء.',
      user_details: 'تفاصيل المستخدم'
    },
    
    // Settings
    settings: {
      title: 'الإعدادات',
      general: 'الإعدادات العامة',
      company: 'معلومات الشركة',
      system: 'إعدادات النظام',
      backup: 'النسخ الاحتياطي والاستعادة',
      company_name: 'اسم الشركة',
      company_logo: 'شعار الشركة',
      company_address: 'عنوان الشركة',
      company_phone: 'هاتف الشركة',
      company_email: 'بريد الشركة الإلكتروني',
      company_website: 'موقع الشركة الإلكتروني',
      company_tax_number: 'الرقم الضريبي',
      currency: 'العملة',
      date_format: 'تنسيق التاريخ',
      language: 'اللغة',
      theme: 'المظهر',
      invoice_prefix: 'بادئة الفاتورة',
      invoice_footer: 'تذييل الفاتورة',
      save_settings: 'حفظ الإعدادات',
      settings_saved_success: 'تم حفظ الإعدادات بنجاح',
      backup_data: 'نسخ البيانات احتياطياً',
      restore_data: 'استعادة البيانات',
      confirm_restore: 'هل أنت متأكد من رغبتك في استعادة البيانات؟ سيؤدي هذا إلى استبدال جميع البيانات الحالية.',
      backup_success: 'تم إنشاء نسخة احتياطية بنجاح',
      restore_success: 'تمت استعادة البيانات بنجاح'
    },
    
    // Validation
    validation: {
      required: 'هذا الحقل مطلوب',
      email: 'يرجى إدخال عنوان بريد إلكتروني صالح',
      min_length: 'يجب أن يحتوي هذا الحقل على {min} أحرف على الأقل',
      max_length: 'يجب ألا يتجاوز هذا الحقل {max} حرفًا',
      min_value: 'يجب أن يكون هذا الحقل {min} على الأقل',
      max_value: 'يجب ألا يتجاوز هذا الحقل {max}',
      match: 'الحقول غير متطابقة',
      numeric: 'يجب أن يكون هذا الحقل رقمًا',
      integer: 'يجب أن يكون هذا الحقل عددًا صحيحًا',
      positive: 'يجب أن يكون هذا الحقل رقمًا موجبًا',
      url: 'يرجى إدخال عنوان URL صالح',
      date: 'يرجى إدخال تاريخ صالح'
    },
    
    // Errors
    errors: {
      unknown: 'حدث خطأ غير معروف',
      server_error: 'حدث خطأ في الخادم',
      network_error: 'خطأ في الشبكة. يرجى التحقق من اتصالك',
      permission_denied: 'تم رفض الإذن',
      not_found: 'لم يتم العثور على المورد',
      validation_failed: 'فشل التحقق من الصحة',
      item_exists: 'العنصر موجود بالفعل',
      firebase_error: 'خطأ في Firebase: {message}'
    }
  };