export default {
    // Common
    common: {
      app_name: 'HCP ERP',
      loading: 'Loading...',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      view: 'View',
      add: 'Add',
      search: 'Search',
      filter: 'Filter',
      reset: 'Reset',
      export: 'Export',
      actions: 'Actions',
      confirm: 'Confirm',
      back: 'Back',
      next: 'Next',
      yes: 'Yes',
      no: 'No',
      close: 'Close',
      logout: 'Logout',
      all: 'All',
      welcome: 'Welcome',
      settings: 'Settings',
      profile: 'Profile',
      dark_mode: 'Dark Mode',
      light_mode: 'Light Mode',
      required: 'Required',
      optional: 'Optional',
      status: 'Status',
      date: 'Date',
      amount: 'Amount',
      price: 'Price',
      total: 'Total',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      address: 'Address',
      notes: 'Notes',
      description: 'Description',
      category: 'Category',
      id: 'ID'
    },
    
    // Auth
    auth: {
      login: 'Login',
      login_to_account: 'Login to your account',
      forgot_password: 'Forgot Password?',
      reset_password: 'Reset Password',
      email: 'Email',
      password: 'Password',
      confirm_password: 'Confirm Password',
      login_error: 'Invalid email or password',
      logout_success: 'You have been logged out',
      session_expired: 'Your session has expired due to inactivity',
      reset_password_instructions: 'Enter your email address and we\'ll send you a link to reset your password',
      reset_password_success: 'Password reset email sent. Check your inbox.'
    },
    
    // Navigation
    nav: {
      dashboard: 'Dashboard',
      customers: 'Customers',
      suppliers: 'Suppliers',
      sales: 'Sales',
      products: 'Products',
      accounting: 'Accounting',
      reports: 'Reports',
      users: 'Users',
      settings: 'Settings'
    },
    
    // Dashboard
    dashboard: {
      title: 'Dashboard',
      total_sales: 'Total Sales',
      total_customers: 'Total Customers',
      total_products: 'Products',
      pending_orders: 'Pending Orders',
      recent_orders: 'Recent Orders',
      sales_overview: 'Sales Overview',
      top_products: 'Top Products',
      view_all: 'View All',
      from_last_month: 'from last month',
      from_last_week: 'from last week'
    },
    
    // Products
    products: {
      title: 'Products Management',
      add_product: 'Add Product',
      edit_product: 'Edit Product',
      delete_product: 'Delete Product',
      product_name: 'Product Name',
      product_category: 'Category',
      product_price: 'Price',
      batch_codes: 'Batch/Codes',
      add_batch_code: 'Add Batch/Code',
      filter_products: 'Filter Products',
      category_all: 'All Categories',
      category_constructional: 'Constructional',
      category_external: 'External',
      category_decorative: 'Decorative',
      price_range: 'Price Range',
      price_min: 'Min',
      price_max: 'Max',
      no_products_found: 'No products found',
      get_started_add_product: 'Get started by adding a new product',
      product_added_success: 'Product added successfully',
      product_updated_success: 'Product updated successfully',
      product_deleted_success: 'Product deleted successfully',
      confirm_delete_product: 'Are you sure you want to delete this product? This action cannot be undone.',
      enter_batch_code: 'Enter batch code',
      showing: 'Showing',
      to: 'to',
      of: 'of',
      products: 'products',
      product_details: 'Product Details'
    },
    
    // Customers
    customers: {
      title: 'Customers Management',
      add_customer: 'Add Customer',
      edit_customer: 'Edit Customer',
      delete_customer: 'Delete Customer',
      customer_name: 'Customer Name',
      customer_type: 'Customer Type',
      phone_number: 'Phone Number',
      address: 'Address',
      discount_rate: 'Discount Rate',
      type_corporate: 'Corporate/Projects',
      type_retail: 'Retail Shops',
      type_individual: 'Individual',
      no_customers_found: 'No customers found',
      get_started_add_customer: 'Get started by adding a new customer',
      customer_added_success: 'Customer added successfully',
      customer_updated_success: 'Customer updated successfully',
      customer_deleted_success: 'Customer deleted successfully',
      confirm_delete_customer: 'Are you sure you want to delete this customer? This action cannot be undone.',
      customer_details: 'Customer Details',
      total_orders: 'Total Orders',
      total_spent: 'Total Spent',
      last_order_date: 'Last Order Date'
    },
    
    // Suppliers
    suppliers: {
      title: 'Suppliers Management',
      add_supplier: 'Add Supplier',
      edit_supplier: 'Edit Supplier',
      delete_supplier: 'Delete Supplier',
      supplier_name: 'Supplier Name',
      phone_number: 'Phone Number',
      address: 'Address',
      no_suppliers_found: 'No suppliers found',
      get_started_add_supplier: 'Get started by adding a new supplier',
      supplier_added_success: 'Supplier added successfully',
      supplier_updated_success: 'Supplier updated successfully',
      supplier_deleted_success: 'Supplier deleted successfully',
      confirm_delete_supplier: 'Are you sure you want to delete this supplier? This action cannot be undone.',
      supplier_details: 'Supplier Details'
    },
    
    // Sales
    sales: {
      title: 'Sales Management',
      invoices: 'Invoices',
      create_invoice: 'Create Invoice',
      edit_invoice: 'Edit Invoice',
      view_invoice: 'View Invoice',
      delete_invoice: 'Delete Invoice',
      invoice_number: 'Invoice Number',
      order_number: 'Order Number',
      invoice_date: 'Invoice Date',
      due_date: 'Due Date',
      customer: 'Customer',
      select_customer: 'Select Customer',
      products: 'Products',
      add_product: 'Add Product',
      select_product: 'Select Product',
      quantity: 'Quantity',
      unit_price: 'Unit Price',
      subtotal: 'Subtotal',
      discount: 'Discount',
      tax: 'Tax',
      total: 'Total',
      payment_method: 'Payment Method',
      payment_status: 'Payment Status',
      payment_notes: 'Payment Notes',
      payment_date: 'Payment Date',
      payment_amount: 'Payment Amount',
      invoice_notes: 'Invoice Notes',
      print_invoice: 'Print Invoice',
      download_invoice: 'Download Invoice',
      send_invoice: 'Send Invoice',
      status_draft: 'Draft',
      status_pending: 'Pending',
      status_processing: 'Processing',
      status_delivered: 'Delivered',
      status_canceled: 'Canceled',
      status_returned: 'Returned',
      payment_status_paid: 'Paid',
      payment_status_partial: 'Partial',
      payment_status_due: 'Due',
      payment_status_overdue: 'Overdue',
      payment_method_cash: 'Cash',
      payment_method_bank_transfer: 'Bank Transfer',
      payment_method_e_wallet: 'E-Wallet',
      payment_method_bank_check: 'Bank Check',
      deposit_amount: 'Deposit Amount',
      deposit_method: 'Deposit Method',
      invoice_created_success: 'Invoice created successfully',
      invoice_updated_success: 'Invoice updated successfully',
      invoice_deleted_success: 'Invoice deleted successfully',
      confirm_delete_invoice: 'Are you sure you want to delete this invoice? This action cannot be undone.',
      return_invoice: 'Return Invoice',
      create_return: 'Create Return',
      return_reason: 'Return Reason',
      return_date: 'Return Date',
      return_products: 'Return Products',
      return_amount: 'Return Amount',
      return_created_success: 'Return created successfully'
    },
    
    // Accounting
    accounting: {
      title: 'Accounting',
      customer_payments: 'Customer Payments',
      supplier_payments: 'Supplier Payments',
      add_payment: 'Add Payment',
      edit_payment: 'Edit Payment',
      delete_payment: 'Delete Payment',
      payment_date: 'Payment Date',
      payment_amount: 'Amount',
      payment_method: 'Payment Method',
      payment_reference: 'Reference',
      payment_notes: 'Notes',
      payment_type: 'Type',
      payment_invoice: 'Invoice',
      payment_customer: 'Customer',
      payment_supplier: 'Supplier',
      payment_added_success: 'Payment added successfully',
      payment_updated_success: 'Payment updated successfully',
      payment_deleted_success: 'Payment deleted successfully',
      confirm_delete_payment: 'Are you sure you want to delete this payment? This action cannot be undone.',
      customer_statement: 'Customer Statement',
      supplier_statement: 'Supplier Statement',
      generate_statement: 'Generate Statement',
      statement_period: 'Statement Period',
      opening_balance: 'Opening Balance',
      closing_balance: 'Closing Balance',
      transaction_date: 'Date',
      transaction_type: 'Type',
      transaction_reference: 'Reference',
      transaction_description: 'Description',
      transaction_debit: 'Debit',
      transaction_credit: 'Credit',
      transaction_balance: 'Balance',
      print_statement: 'Print Statement',
      export_statement: 'Export Statement'
    },
    
    // Reports
    reports: {
      title: 'Reports',
      sales_report: 'Sales Report',
      inventory_report: 'Inventory Report',
      financial_report: 'Financial Report',
      customer_report: 'Customer Report',
      supplier_report: 'Supplier Report',
      date_range: 'Date Range',
      start_date: 'Start Date',
      end_date: 'End Date',
      generate_report: 'Generate Report',
      export_report: 'Export Report',
      print_report: 'Print Report',
      total_sales: 'Total Sales',
      total_cost: 'Total Cost',
      total_profit: 'Total Profit',
      profit_margin: 'Profit Margin',
      top_selling_products: 'Top Selling Products',
      top_customers: 'Top Customers',
      monthly_sales: 'Monthly Sales',
      sales_by_category: 'Sales by Category',
      sales_by_payment_method: 'Sales by Payment Method'
    },
    
    // Users
    users: {
      title: 'Users Management',
      add_user: 'Add User',
      edit_user: 'Edit User',
      delete_user: 'Delete User',
      user_name: 'Name',
      user_email: 'Email',
      user_password: 'Password',
      user_confirm_password: 'Confirm Password',
      user_role: 'Role',
      user_status: 'Status',
      role_admin: 'Administrator',
      role_supervisor: 'Supervisor',
      role_user: 'User',
      status_active: 'Active',
      status_inactive: 'Inactive',
      last_login: 'Last Login',
      created_date: 'Created Date',
      no_users_found: 'No users found',
      user_added_success: 'User added successfully',
      user_updated_success: 'User updated successfully',
      user_deleted_success: 'User deleted successfully',
      confirm_delete_user: 'Are you sure you want to delete this user? This action cannot be undone.',
      user_details: 'User Details'
    },
    
    // Settings
    settings: {
      title: 'Settings',
      general: 'General Settings',
      company: 'Company Information',
      system: 'System Settings',
      backup: 'Backup & Restore',
      company_name: 'Company Name',
      company_logo: 'Company Logo',
      company_address: 'Company Address',
      company_phone: 'Company Phone',
      company_email: 'Company Email',
      company_website: 'Company Website',
      company_tax_number: 'Tax Number',
      currency: 'Currency',
      date_format: 'Date Format',
      language: 'Language',
      theme: 'Theme',
      invoice_prefix: 'Invoice Prefix',
      invoice_footer: 'Invoice Footer',
      save_settings: 'Save Settings',
      settings_saved_success: 'Settings saved successfully',
      backup_data: 'Backup Data',
      restore_data: 'Restore Data',
      confirm_restore: 'Are you sure you want to restore data? This will replace all current data.',
      backup_success: 'Backup created successfully',
      restore_success: 'Data restored successfully'
    },
    
    // Validation
    validation: {
      required: 'This field is required',
      email: 'Please enter a valid email address',
      min_length: 'This field must be at least {min} characters',
      max_length: 'This field must not exceed {max} characters',
      min_value: 'This field must be at least {min}',
      max_value: 'This field must not exceed {max}',
      match: 'The fields do not match',
      numeric: 'This field must be a number',
      integer: 'This field must be an integer',
      positive: 'This field must be a positive number',
      url: 'Please enter a valid URL',
      date: 'Please enter a valid date'
    },
    
    // Errors
    errors: {
      unknown: 'An unknown error occurred',
      server_error: 'Server error occurred',
      network_error: 'Network error. Please check your connection',
      permission_denied: 'Permission denied',
      not_found: 'Resource not found',
      validation_failed: 'Validation failed',
      item_exists: 'Item already exists',
      firebase_error: 'Firebase error: {message}'
    }
  };